import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FB", padding: 16 },
  header: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 20,
    marginTop: 10,
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#E9ECEF",
    borderRadius: 14,
    padding: 4,
    marginBottom: 20,
  },
  tab: { flex: 1, paddingVertical: 10, alignItems: "center", borderRadius: 11 },
  activeTab: {
    backgroundColor: "#FFFFFF",
    elevation: 3,
    ...Platform.select({
      web: { boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.1)" },
      default: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
    }),
  },
  tabText: { fontWeight: "600", color: "#6C757D", fontSize: 14 },
  activeTabText: { color: "#007AFF" },
  chartCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  chartWrapper: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 20,
  },
  totalAmount: { fontSize: 20, fontWeight: "bold", color: "#1A1A1A" },
  totalLabel: {
    fontSize: 10,
    color: "#95A5A6",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  legendWrapper: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F1F3F5",
    paddingTop: 20,
  },
  legendItem: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  catName: { fontSize: 15, fontWeight: "600", color: "#2D3436" },
  catPercent: { fontSize: 12, color: "#A0A0A0", marginTop: 2 },
  catValue: { fontSize: 16, fontWeight: "700", color: "#2D3436" },
  indicator: { width: 20, height: 3, borderRadius: 2, marginTop: 4 },
  emptyText: {
    textAlign: "center",
    color: "#95A5A6",
    marginVertical: 20,
    fontSize: 15,
  },
  monthSelector: {
    marginBottom: 20,
  },
  monthScrollContent: {
    paddingHorizontal: 4,
  },
  monthButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginHorizontal: 4,
    borderRadius: 12,
    backgroundColor: "#E9ECEF",
  },
  monthButtonActive: {
    backgroundColor: "#007AFF",
    elevation: 2,
    ...Platform.select({
      web: { boxShadow: "0px 2px 6px rgba(0, 122, 255, 0.3)" },
      default: {
        shadowColor: "#007AFF",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
    }),
  },
  monthButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6C757D",
  },
  monthButtonTextActive: {
    color: "#FFFFFF",
  },
  yearSelector: {
    marginBottom: 20,
  },
  yearButtonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  yearButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#E9ECEF",
    minWidth: 80,
    alignItems: "center",
  },
  yearButtonActive: {
    backgroundColor: "#007AFF",
    elevation: 2,
    ...Platform.select({
      web: { boxShadow: "0px 2px 6px rgba(0, 122, 255, 0.3)" },
      default: {
        shadowColor: "#007AFF",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
    }),
  },
  yearButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#6C757D",
  },
  yearButtonTextActive: {
    color: "#FFFFFF",
  },
  periodButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
    marginBottom: 20,
    elevation: 2,
    ...Platform.select({
      web: { boxShadow: "0px 2px 4px rgba(0, 0, 0, 0.08)" },
      default: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
    }),
  },
  periodButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  periodButtonIcon: {
    fontSize: 12,
    color: "#007AFF",
  },
  focusedCategory: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
    marginTop: 4,
  },
  focusedPercentage: {
    fontSize: 28,
    fontWeight: "800",
    color: "#9b59b6",
    marginTop: 4,
  },
  focusedAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6C757D",
    marginTop: 2,
  },
  chargesList: {
    marginLeft: 0,
    marginRight: 0,
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  chargeItem: {
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    borderLeftWidth: 4,
    borderLeftColor: "#9b59b6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  chargeIconBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f0f2f5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#e1e4e8",
  },
  chargeIcon: {
    fontSize: 18,
  },
  chargeInfo: {
    flex: 1,
    justifyContent: "center",
  },
  chargeLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2c3e50",
  },
  chargePayeur: {
    fontSize: 11,
    color: "#7f8c8d",
    marginTop: 2,
  },
  chargeMontantContainer: {
    alignItems: "flex-end",
    justifyContent: "center",
    marginLeft: 10,
  },
  chargeMontant: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2c3e50",
  },
  chargeDate: {
    fontSize: 11,
    color: "#95A5A6",
    marginTop: 2,
  },
});
