import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { 
        flex: 1, 
        padding: 20, 
        backgroundColor: '#f4f7f9'
    },
    header: { 
        fontSize: 24, 
        fontWeight: 'bold', 
        color: '#2c3e50',
        marginBottom: 20, 
        textAlign: 'center',
    },
    loading: { 
        textAlign: 'center', 
        marginTop: 50,
        fontSize: 16,
        color: '#7f8c8d',
    },
    
    addButton: { 
        backgroundColor: '#27ae60',
        padding: 14, 
        borderRadius: 8, 
        marginBottom: 15, 
        alignItems: 'center',
        shadowColor: '#27ae60',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    addButtonText: { 
        color: '#fff', 
        fontWeight: '700',
        fontSize: 16,
    },
    formContainer: { 
        backgroundColor: '#fff', 
        padding: 18, 
        borderRadius: 12, 
        marginBottom: 20, 
        borderWidth: 1, 
        borderColor: '#eee',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    input: { 
        borderWidth: 1, 
        borderColor: '#ddd', 
        padding: 12, 
        marginBottom: 15, 
        borderRadius: 8,
        backgroundColor: '#f9f9f9',
    },
    payeurInfo: { 
        marginBottom: 15, 
        fontStyle: 'italic', 
        fontSize: 14,
        color: '#7f8c8d',
    },
    
    list: { 
        flex: 1,
        paddingBottom: 20,
    },
    depenseItem: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 10,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderLeftWidth: 5,
        borderLeftColor: '#3498db',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    depenseInfo: { flex: 3 },
    depenseDetails: { flex: 2, alignItems: 'flex-end' },
    depenseDesc: { fontSize: 17, fontWeight: '600', color: '#333' },
    depenseDate: { fontSize: 12, color: '#95a5a6', marginTop: 3 },
    depenseAmount: { fontSize: 18, fontWeight: 'bold', color: '#e67e22' },
    depensePayer: { fontSize: 13, color: '#27ae60', marginTop: 3, fontWeight: '500' },
});