import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f7fa',
        paddingHorizontal: 10,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f7fa',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: 16,
        color: '#7f8c8d',
        textAlign: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2c3e50', 
        paddingVertical: 15,
        paddingHorizontal: 10,
        marginBottom: 5,
    },
    monthCard: {
        backgroundColor: '#ffffff',
        borderRadius: 10,
        padding: 15,
        marginVertical: 8,
        marginHorizontal: 5,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
        borderLeftWidth: 5,
        borderLeftColor: '#34495e',
    },
    monthTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2c3e50',
        flex: 2,
    },
    statusBadge: {
        backgroundColor: '#2ecc71',
        color: '#ffffff',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 15,
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
        marginHorizontal: 10,
    },
    detailText: {
        fontSize: 16,
        color: '#3498db',
        fontWeight: '500',
    },
});