import { StyleSheet } from "react-native";
import { colors, spacing, radius, shadows } from "../../../theme.style";

export const styles = StyleSheet.create({

  typeSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.neutral100,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xl,
    borderWidth: 1,
    borderColor: colors.neutral500,
  },
  typeSelectorLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm + 2,
  },
  typeSelectorIcon: {
    fontSize: 22,
  },
  typeSelectorLabel: {
    fontSize: 12,
    color: colors.textMuted,
    marginBottom: 2,
  },
  typeSelectorValue: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  stepperContainer: {
    marginBottom: spacing.xl,
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  stepperLabel: {
    fontSize: 15,
    color: colors.textSecondary,
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.neutral500,
    borderRadius: radius.md,
    overflow: "hidden",
    backgroundColor: colors.surface,
  },
  stepBtn: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.neutral100,
  },
  stepBtnDisabled: {
    opacity: 0.35,
  },
  stepBtnText: {
    fontSize: 20,
    color: colors.textPrimary,
    lineHeight: 24,
  },
  stepValue: {
    paddingHorizontal: spacing.lg,
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
    minWidth: 40,
    textAlign: "center",
  },
  dayPickerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.neutral100,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xl,
    borderWidth: 1,
    borderColor: colors.neutral500,
  },
  dayPickerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  dayPickerText: {
    fontSize: 15,
    color: colors.textPrimary,
  },
  chipGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  chip: {
    width: "14%",
    aspectRatio: 1, 
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 0, 
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.neutral500,
    backgroundColor: colors.surface,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipDisabled: {
    opacity: 0.4,
  },
  chipText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  chipTextSelected: {
    color: colors.surface,
  },
  dateInputContainer: {
    marginBottom: spacing.xxs,
  },
  dateFinRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.sm,
  },
  dateFinLabelWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  dateFinToggle: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.neutral500,
    backgroundColor: colors.surface,
  },
  dateFinToggleActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  dateFinToggleText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  dateFinToggleTextActive: {
    color: colors.primary,
  },
  echeancierContainer: {
    marginBottom: spacing.xl,
    width: "100%",
  },
  echeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
    marginBottom: spacing.sm,
    width: "100%",
  },
  echeInputDate: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 12,
    borderWidth: 1,
    borderColor: colors.neutral200,
    color: colors.textPrimary,
    minWidth: 0,
  },
  echeInputMontant: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 12,
    borderWidth: 1,
    borderColor: colors.neutral200,
    color: colors.textPrimary,
    textAlign: "right",
    minWidth: 0,
  },
  echeDeleteBtn: {
    padding: spacing.xs,
  },
  echeAddButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: colors.primary,
    marginTop: spacing.xs,
  },
  echeAddText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "600",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.neutral600,
    marginVertical: spacing.xl,
  },
});