import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  mainView: {
    flex: 1,
    backgroundColor: "#f4f7f9",
  },
  container: {
    flex: 1,
    paddingHorizontal: 15,
    paddingTop: 10,
  },
  loading: {
    textAlign: "center",
    marginTop: 50,
    fontSize: 18,
    color: "#5bc0de",
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 20,
    backgroundColor: "#f4f7f9",
  },
  userInfo: {
    flex: 1,
  },
  welcomeText: {
    fontSize: 22,
    fontWeight: "800",
    color: "#2c3e50",
    letterSpacing: -0.5,
  },
  badge: {
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  badgeSolo: {
    backgroundColor: "#e0e6ed",
  },
  badgeShared: {
    backgroundColor: "#d1e9ff",
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "700",
  },
  badgeTextSolo: {
    color: "#546e7a",
  },
  badgeTextShared: {
    color: "#1e88e5",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: 30,
    textAlign: "center",
  },
  historyCard: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 6,
  },
  historyNavigator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 150,
  },
  navArrow: {
    padding: 10,
    opacity: 0.6,
  },
  navArrowText: {
    fontSize: 28,
    fontWeight: "200",
    color: "#3498db",
  },
  chartArea: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
    height: "100%",
    paddingTop: 45,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sectionTitleHeader: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2c3e50",
  },
  switchContainer: {
    flexDirection: 'row',
    backgroundColor: '#f0f2f5',
    borderRadius: 20,
    padding: 2,
    borderWidth: 1,
    borderColor: '#e0e4e8',
  },
  switchButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 18,
  },
  switchButtonActive: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  switchText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#95a5a6',
  },
  switchTextActive: {
    color: '#3498db',
  },
  historyTotalLabel: {
    fontWeight: "700",
    marginBottom: 4,
    textAlign: "center",
  },
  actionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingBottom: 20,
  },
  actionButton: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 12,
    width: "48%",
    marginBottom: 15,
    alignItems: "center",
    justifyContent: "center",
    minHeight: width * 0.25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    borderLeftWidth: 4,
    borderLeftColor: "#3498db",
  },
  actionText: {
    fontWeight: "700",
    color: "#2c3e50",
    textAlign: "center",
    fontSize: 15,
  },
  soloInfoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  soloTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: 10,
  },
  soloDescription: {
    fontSize: 14,
    color: "#7f8c8d",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  inviteButton: {
    backgroundColor: "#3498db",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
  },
  inviteButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
  userIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  menuDropdown: {
    position: "absolute",
    top: 60,
    right: 20,
    backgroundColor: "#fff",
    borderRadius: 12,
    width: 180,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
  },
  menuItemText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2c3e50",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginVertical: 4,
  },
  householdMenuDropdown: {
    position: "absolute",
    top: 100,
    left: 20,
    backgroundColor: "#fff",
    borderRadius: 15,
    width: 220,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 12,
    borderWidth: 1,
    borderColor: "#f0f0f0",
    zIndex: 1000,
  },
  householdMenuTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#bdc3c7",
    textTransform: "uppercase",
    marginBottom: 8,
    marginLeft: 10,
    letterSpacing: 1,
  },
  householdItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    gap: 12,
    marginBottom: 4,
  },
  activeHouseholdItem: {
    backgroundColor: "#f0f7ff",
    borderLeftWidth: 3,
    borderLeftColor: "#3498db",
  },
  householdItemText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2c3e50",
    flex: 1,
  },
  activeHouseholdText: {
    color: "#3498db",
    fontWeight: "700",
  },
  addHouseholdItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
    marginTop: 5,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  addHouseholdText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3498db",
  },
  navArrowDisabled: {
    opacity: 0.3,
  },
  navArrowTextDisabled: {
    color: "#bdc3c7",
  },
});
