import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  editFormContainer: {
    padding: 16,
    backgroundColor: "#f8f8f8",
  },
  editSectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
  },
  editLabel: {
    color: "#8E8E93",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  editRow: {
    flexDirection: "row",
    marginBottom: 0,
  },
  selectorContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 45,
    marginTop: 4,
    borderWidth: 1,
    borderColor: "#EFEFEF",
  },
  miniUserText: {
    color: "#333",
    fontSize: 14,
    fontWeight: "500",
  },
  inputFieldContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 2,
    borderWidth: 1,
    borderColor: "#EFEFEF",
  },
  editInputActive: {
    flex: 1,
    fontSize: 17,
    fontWeight: "600",
    color: "#333",
  },
  saveButton: {
    backgroundColor: "#27ae60",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
  },
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 15,
    marginBottom: 1,
  },
  payorCard: {
    borderLeftWidth: 4,
    borderLeftColor: "#27ae60",
    marginBottom: 10,
    marginTop: 5,
    borderRadius: 8,
    overflow: "hidden",
    elevation: 1,
  },
    cardAmount: {
    fontSize: 17,
    fontWeight: "600",
    minWidth: 70,
    textAlign: "right",
    color: "#333",
  },
});