import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fa",
    paddingHorizontal: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f7fa",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: "#7f8c8d",
    textAlign: "center",
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#2c3e50",
    paddingVertical: 15,
    paddingHorizontal: 10,
    marginBottom: 5,
  },
  monthCard: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 15,
    marginVertical: 5,
    marginHorizontal: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    borderLeftWidth: 5,
    borderLeftColor: "#34495e",
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#2c3e50",
    flex: 2,
  },
  statusBadge: {
    backgroundColor: "#2ecc71",
    color: "#ffffff",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 15,
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    marginHorizontal: 10,
  },
  detailText: {
    fontSize: 16,
    color: "#3498db",
    fontWeight: "500",
  },
  yearSection: {
    marginBottom: 15,
    borderRadius: 10,
    backgroundColor: "#f5f5f5",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  yearHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    backgroundColor: "#2c3e50",
  },
  yearText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
  },
  arrow: {
    fontSize: 18,
    color: "#ffffff",
  },
  yearContent: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingHorizontal: 10,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
  },
  monthSubCard: {
    backgroundColor: "#ecf0f1",
    marginBottom: 8,
    marginTop: 5,
    paddingHorizontal: 15,
    borderRadius: 6,
    borderWidth: 0,
  },
});
