import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    paddingHorizontal: 20,
  },
  monthSelector: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 15,
    marginTop: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  monthLabel: {
    fontSize: 18,
    fontWeight: "800",
    color: "#2c3e50",
    textTransform: "capitalize",
    minWidth: 150,
    textAlign: "center",
  },
  monthArrow: {
    padding: 8,
    backgroundColor: "#F1F3F5",
    borderRadius: 10,
  },
  mainSavingsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  cardLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7f8c8d",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bigAmount: {
    fontSize: 36,
    fontWeight: "900",
    marginVertical: 5,
  },
  miniStatsRow: {
    flexDirection: "row",
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "#F1F3F5",
  },
  miniStatLabel: {
    fontSize: 10,
    color: "#95a5a6",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  miniStatValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2c3e50",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    marginTop: 10,
  },
  titleWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#2c3e50",
  },
  tireliresList: {
    marginTop: 10,
    gap: 15,
  },
  tirelireCard: {
    backgroundColor: "#FFF",
    padding: 18,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#edf2f7",
  },
  tirelireHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  tirelireName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#34495e",
  },
  tirelireAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: "#7f8c8d",
  },
  objectivSmall: {
    fontSize: 12,
    color: "#95a5a6",
    fontWeight: "400",
  },
  progressBarContainer: {
    height: 10,
    backgroundColor: "#f1f3f5",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#27ae60",
    borderRadius: 5,
  },
  remainingText: {
    fontSize: 11,
    color: "#7f8c8d",
    marginTop: 8,
    fontStyle: "italic",
  },
  dispatchButton: {
    backgroundColor: "#27ae60",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 10,
  },
  dispatchButtonText: {
    color: "#FFF",
    fontWeight: "800",
    fontSize: 16,
  },
  addButtonSecondary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    marginTop: 25,
    borderWidth: 2,
    borderColor: "#3498db",
    borderStyle: "dashed",
    borderRadius: 15,
    gap: 10,
    marginBottom: 40,
  },
  addButtonSecondaryText: {
    color: "#3498db",
    fontWeight: "700",
  },
  warningBox: {
    backgroundColor: "#FFF5F5",
    padding: 18,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#FEB2B2",
    alignItems: "center",
  },
  warningText: {
    color: "#C53030",
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 20,
    padding: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#2c3e50",
    marginBottom: 20,
    textAlign: "center",
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#7f8c8d",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 15,
    marginTop: 10,
  },
  btnCancel: {
    flex: 1,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#F1F3F5",
  },
  btnCancelText: {
    color: "#7f8c8d",
    fontWeight: "700",
  },
  btnConfirm: {
    flex: 2,
    padding: 15,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#3498db",
  },
  btnConfirmText: {
    color: "#FFF",
    fontWeight: "700",
  },
  dispatchItem: {
    padding: 15,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  dispatchItemName: {
    fontWeight: "700",
    color: "#2c3e50",
  },
  dispatchItemReste: {
    fontSize: 12,
    color: "#27ae60",
    fontWeight: "600",
  },
  breakInfoText: {
    fontSize: 12,
    color: "#d35400",
    textAlign: "center",
    fontStyle: "italic",
  },
  breakInfoBox: {
    backgroundColor: "#fdf2e9",
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
  },
  breakCurrentAmount: {
    textAlign: "center",
    marginBottom: 20,
    color: "#27ae60",
    fontSize: 16,
    fontWeight: "700",
  },
  breakTirelireName: {
    textAlign: "center",
    marginBottom: 15,
    color: "#2c3e50",
    fontWeight: "600",
  },
  totalAccumulatedContainer: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginBottom: 15,
    padding: 15,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#ecf0f1",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  totalAccumulatedLabel: {
    fontSize: 13,
    color: "#7f8c8d",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  totalAccumulatedAmount: {
    fontSize: 24,
    fontWeight: "800",
    color: "#2c3e50",
    marginTop: 4,
  },
  totalAccumulatedIcon: {
    backgroundColor: "#ebf5fb",
    padding: 10,
    borderRadius: 50,
  },
  currentMonthBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#27ae60",
    marginRight: 6,
  },
  currentMonthText: {
    fontSize: 12,
    color: "#27ae60",
    fontWeight: "600",
  },
  infoBox: {
    backgroundColor: "#fcf3cf",
    padding: 8,
    borderRadius: 8,
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  infoText: {
    fontSize: 12,
    color: "#d35400",
    marginLeft: 8,
    flex: 1,
    fontStyle: "italic",
  },
});
